name: CI Check

permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths: &paths
      - 'app/**'
      - '*.gradle.kts'
      - 'gradle/**'
      - '.github/workflows/dev-release.yml'
  pull_request:
    branches: [ main ]
    paths: *paths

jobs:
  check:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Gradle
        uses: ./.github/actions/gradle-setup

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Run Unit Tests
        run: ./gradlew :app:testDebugUnitTest
